CREATE USER goserver WITH PASSWORD 'server' LOGIN;

GRANT CONNECT ON DATABASE tda25 TO goserver;
GRANT USAGE ON SCHEMA public TO goserver;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO goserver;

